version: "3.9"

services:
  db:
    image: postgres:16
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydatabase
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  app:   
    image: dep_img:latest  
    container_name: dep_app
    depends_on:
      - db
    restart: always
    environment:
      ConnectionStrings__Default: "Host=db;Port=5432;Database=mydatabase;Username=myuser;Password=mypassword"
    ports:
      - "5000:5001"

volumes:
  db_data:
